import {createClient} from '@supabase/supabase-js';
import {escapeHtml as e, readingState, siteState} from './domain.js';
import './style.css';
import testPreview from './test-preview.json';
const isPreview=()=>location.hash.startsWith('#demo/');
import './dark.css';
import './schematic.css';
import {systemDiagram,bindDiagram,findingCards} from './schematic.js';
import {icon} from './icons.js';

const url=import.meta.env.VITE_SUPABASE_URL, key=import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;
const db=url&&key?createClient(url,key):null;
const root=document.querySelector('#app');
let activationToken=location.hash.startsWith('#activate/')?location.hash.slice(10):null;
let passwordSetup=location.hash==='#set-password';
const names={overview:'Analyseoversikt',sites:'Anlegg',alarms:'Alarmer',trends:'Måledata',reports:'Analyse & rapporter',analysis:'Analysehub',integrations:'Datakilder'};
const symbols={overview:'◫',sites:'▥',alarms:'△',trends:'⌁',reports:'▤',analysis:'✧',integrations:'⊞'};
const emptyData=()=>({sites:[],sensors:[],latest_readings:[],alarms:[],events:[],reports:[],integrations:[],analysis_runs:[],organizations:[]});
let session=null, data=emptyData(), loading=true, failure='', updated=null, generation=0, historyGeneration=0, history=[], historyBusy=false, historyError='', selectedSensor='', period='24', selectedReport='', reportTab='overview';
const time=v=>v?new Date(v).toLocaleString('nb-NO',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit'}):'Ikke mottatt';
const val=v=>v==null?'—':new Intl.NumberFormat('nb-NO',{maximumFractionDigits:2}).format(v);
const subset=(t,id)=>data[t].filter(x=>!id||x.site_id===id);
const stateLabels={warning:'Bør følges opp',info:'Informasjon',normal:'Normal drift',alarm:'Aktiv alarm',unknown:'Ukjent status',fresh:'Oppdatert',missing:'Ingen måling',stale:'Utdatert',invalid:'Usikker verdi'};
const badge=s=>`<span class="badge ${e(s)}"><i></i>${e(stateLabels[s]||s)}</span>`;
const nav=(page,text,cls='')=>`<a class="${cls}" href="#${isPreview()&&page!=="login"?"demo/":""}${page}">${text}</a>`;
const blank=(symbol,title,description,action='')=>`<div class="empty"><span class="empty-icon">${icon(symbol)}</span><h3>${title}</h3><p>${description}</p>${action}</div>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
const siteName=id=>e(data.sites.find(s=>s.id===id)?.name||'Anlegg');
const testLabel=s=>s?.is_test?'<span class="test-tag">TEST</span>':'';
function current(){const [page,id]=(location.hash.slice(1).replace(/^demo\//,'')||'login').split('/');return {page,id};}
function status(site){return siteState(subset('sensors',site.id),subset('latest_readings',site.id),subset('alarms',site.id));}
function stats(items){return `<div class="stats">${items.map(([label,value,desc,symbol])=>`<article class="stat"><div>${label}<span>${icon(symbol)}</span></div><strong>${value}</strong><small>${desc}</small></article>`).join('')}</div>`;}
function findingSeverityLabel(s){return {critical:'Kritisk',warning:'Bør undersøkes',normal:'Normal trend',info:'Informasjon'}[s]||'Ukjent';}
function allFindings(siteId){return data.reports.filter(r=>!siteId||r.site_id===siteId).flatMap(r=>(r.findings||[]).map((f,i)=>({...f,report_id:r.id,report_title:r.title,site_id:r.site_id,key:r.id+'-'+i})));}
function findingList(findings,limit=6){
 const rows=findings.slice(0,limit);
 return rows.length?`<div class="insight-list">${rows.map(f=>`<button class="insight-row report-open" data-id="${e(f.report_id)}"><span class="signal-dot ${e(f.severity||'unknown')}"></span><span class="insight-copy"><strong>${e(f.title)}</strong><small>${siteName(f.site_id)} · ${e(f.report_title)}</small></span><span class="severity ${e(f.severity||'unknown')}">${e(findingSeverityLabel(f.severity))}</span><span class="row-arrow">→</span></button>`).join('')}</div>`:blank('✧','Ingen analysefunn ennå','Når trendanalysen finner et mønster som bør vurderes, vises det her.');
}
function siteList(){return data.sites.length?`<div class="site-cards">${data.sites.map(s=>{const fs=allFindings(s.id),warnings=fs.filter(f=>f.severity==='warning'||f.severity==='critical').length,latest=subset('latest_readings',s.id).sort((a,b)=>b.observed_at.localeCompare(a.observed_at))[0];return `<a class="site-card" href="#${isPreview()?'demo/':''}site/${e(s.id)}"><div class="site-card-top"><div><span class="eyebrow">ANLEGG</span><h3>${e(s.name)} ${testLabel(s)}</h3><p>${e(s.address||'Adresse ikke registrert')}</p></div><span class="site-score ${warnings?'warning':'normal'}">${warnings?warnings+' funn':'Rolig'}</span></div><div class="site-card-kpis"><span><strong>${subset('sensors',s.id).length}</strong>Målepunkter</span><span><strong>${fs.length}</strong>Analysefunn</span><span><strong>${time(latest?.observed_at)}</strong>Siste data</span></div><div class="site-card-link">Åpne analyse →</div></a>`;}).join('')}</div>`:blank('▥',session?'Ingen anlegg registrert':'Ingen anlegg i visningen',session?'Når et anlegg er registrert, vises analysefunn og datakvalitet her.':'Åpne testvisningen for å se hvordan analysearbeidsflaten fungerer.',session?nav('integrations','Se datakilder →','button secondary'):nav('demo/overview','Åpne testvisning →','button'));}
function overview(){const findings=allFindings(),attention=findings.filter(f=>f.severity==='warning'||f.severity==='critical'),stale=data.sensors.filter(s=>readingState(data.latest_readings.find(r=>r.sensor_id===s.id),s)!=='fresh').length;return `<div class="hero-heading"><div><div class="eyebrow">ENVATEC SMARTDRIFT · INTERN ANALYSE</div><h1>Finn mønstrene før de blir alarmer.</h1><p>Et analyseverktøy for gradvise avvik, ineffektiv drift og kombinasjoner av signaler som normalt ikke fanges av faste alarmgrenser.</p></div><div class="hero-chip"><span></span>Analysearbeidsflate</div></div>
<div class="analysis-stats">
 <article><span>Anlegg i analyse</span><strong>${data.sites.length}</strong><small>Registrerte datakilder</small></article>
 <article><span>Funn som bør vurderes</span><strong>${attention.length}</strong><small>Trend- og korrelasjonsavvik</small></article>
 <article><span>Totale analysefunn</span><strong>${findings.length}</strong><small>Fra tilgjengelige rapporter</small></article>
 <article><span>Datapunkter å kontrollere</span><strong>${stale}</strong><small>Mangler / utdaterte signaler</small></article>
</div>
<div class="cockpit-grid"><section class="panel priority-panel"><div class="panel-title"><div><span class="eyebrow">PRIORITERT</span><h2>Funn som fortjener oppmerksomhet</h2></div>${nav('reports','Åpne analysehub →','text-link')}</div>${findingList(attention.length?attention:findings,5)}</section>
<section class="panel method-panel"><div class="panel-title"><div><span class="eyebrow">ANALYSELOGIKK</span><h2>Hva Smartdrift ser etter</h2></div></div><div class="method-grid"><article><span>01</span><strong>Gradvis drift</strong><p>Verdier som sakte flytter seg uten å krysse alarmgrensen.</p></article><article><span>02</span><strong>Brudd i sammenheng</strong><p>Flow, ΔT, effekt eller ventilposisjon som ikke lenger følger forventet forhold.</p></article><article><span>03</span><strong>Unormal energiprofil</strong><p>Last eller driftstid som avviker fra sammenlignbar drift.</p></article><article><span>04</span><strong>Datakvalitet</strong><p>Sensorer som stopper, blir utdaterte eller utvikler usannsynlige mønstre.</p></article></div></section></div>
<section class="portfolio-section"><div class="section-heading"><div><span class="eyebrow">PORTEFØLJE</span><h2>Anlegg</h2></div><span class="muted">Klikk et anlegg for detaljert analyse</span></div>${siteList()}</section>`; }
function eventList(id,limit=50){const rows=subset('events',id).slice(0,limit);return rows.length?`<ul class="events">${rows.map(x=>`<li><span class="event-dot"></span><div><strong>${e(x.message)}</strong><small>${siteName(x.site_id)} · ${time(x.occurred_at)}</small></div></li>`).join('')}</ul>`:blank('◷','Ingen hendelser ennå','Hendelser vises når anleggsdata blir tilgjengelige.');}
function alarmList(id){const rows=subset('alarms',id);return rows.length?table(['Alarm','Anlegg','Prioritet','Tilstand','Registrert'],rows.map(a=>`<tr><td><strong>${e(a.title)}</strong><small>${e(a.description)}</small></td><td>${siteName(a.site_id)}</td><td>${e({critical:'Kritisk',warning:'Advarsel',info:'Informasjon'}[a.severity])}</td><td>${a.state==='active'?`<span class="severity ${a.severity==='critical'?'critical':a.severity==='warning'?'warning':'unknown'}">${e({critical:'Kritisk',warning:'Bør følges opp',info:'Informasjon'}[a.severity])}</span>`:badge('Løst')}</td><td>${time(a.occurred_at)}</td></tr>`)):blank('△','Ingen registrerte alarmer','Dette betyr ikke at anlegget er verifisert i normal drift. Alarmkilden må være tilkoblet.');}
function sensors(id){const rows=subset('sensors',id);return rows.length?table(['Målepunkt','Verdi','Datakvalitet','Sist målt'],rows.map(s=>{const r=data.latest_readings.find(r=>r.sensor_id===s.id);return `<tr><td><strong>${e(s.name)}</strong><small>${e(s.metric)}</small></td><td class="reading">${val(r?.value)} <span>${e(s.unit)}</span></td><td>${badge(readingState(r,s))}</td><td>${time(r?.observed_at)}</td></tr>`;})):blank('⌁','Ingen målepunkter registrert','Temperatur, flow, effekt og energiforbruk vises når sensorer er koblet til.');}
function detail(id){const site=data.sites.find(s=>s.id===id);if(!site)return blank('▥','Anlegget er ikke tilgjengelig','Anlegget finnes ikke, eller du mangler tilgang.',nav('sites','Til anleggsoversikten','button secondary'));const findings=allFindings(id),attention=findings.filter(f=>f.severity==='warning'||f.severity==='critical'),reportsForSite=data.reports.filter(r=>r.site_id===id),latestReport=reportsForSite[0];const quality=subset('sensors',id).filter(s=>readingState(data.latest_readings.find(r=>r.sensor_id===s.id),s)==='fresh').length;const total=subset('sensors',id).length;return `<div class="detail-hero"><div>${nav('sites','← Alle anlegg','text-link')}<div class="eyebrow">ANLEGGSANALYSE</div><h1>${e(site.name)} ${testLabel(site)}</h1><p>${e(site.address||'Adresse ikke registrert')}</p></div><div class="detail-actions">${nav('trends/'+id,'Utforsk måledata','button secondary')}${latestReport?`<button class="button report-open" data-id="${e(latestReport.id)}">Åpne siste rapport →</button>`:''}</div></div>
<div class="analysis-stats compact"><article><span>Funn å undersøke</span><strong>${attention.length}</strong><small>Ikke nødvendigvis SD-alarmer</small></article><article><span>Totale funn</span><strong>${findings.length}</strong><small>Alle klassifiseringer</small></article><article><span>Datakvalitet</span><strong>${total?Math.round(quality/total*100):0}%</strong><small>${quality} av ${total} oppdaterte</small></article><article><span>Rapporter</span><strong>${reportsForSite.length}</strong><small>Lagrede analyser</small></article></div>
<div class="cockpit-grid"><section class="panel priority-panel"><div class="panel-title"><div><span class="eyebrow">ANALYSEFUNN</span><h2>Mønstre og avvik</h2></div><span class="muted">${findings.length} funn</span></div>${findingList(attention.length?attention:findings,8)}</section>
<section class="panel signal-panel"><div class="panel-title"><div><span class="eyebrow">SIGNALER</span><h2>Datagrunnlag</h2></div>${nav('trends/'+id,'Historikk →','text-link')}</div><div class="signal-summary"><div class="signal-ring" style="--score:${total?Math.round(quality/total*100):0}"><strong>${total?Math.round(quality/total*100):0}%</strong><span>oppdatert</span></div><div><h3>${total} målepunkter i analyse</h3><p>Smartdrift bruker tidsserier og sammenhengen mellom signalene. Den grafiske SD-visningen håndteres i eksisterende system.</p></div></div></section></div>
<section class="panel"><div class="panel-title"><div><span class="eyebrow">RÅDATA</span><h2>Sensorer og siste verdier</h2></div>${nav('trends/'+id,'Åpne trendverktøy →','text-link')}</div>${sensors(id)}</section>
<div class="two-col"><section class="panel"><div class="panel-title"><h2>Standardalarmer</h2><span class="muted">Fra tilkoblede kilder</span></div>${alarmList(id)}</section><section class="panel"><div class="panel-title"><h2>Hendelseslogg</h2></div>${eventList(id,8)}</section></div>`;}
function chart(){if(historyBusy)return blank('◷','Henter målinger …','');if(historyError)return `<div role="alert" class="error">${e(historyError)}</div>`;if(!history.length)return blank('⌁','Ingen målinger i valgt periode','Velg et målepunkt og tidsrom. Grafen vises først når reelle målinger finnes.');const good=history.filter(x=>x.quality==='good');if(!good.length)return blank('⌁','Ingen gyldige målinger','Målingene i perioden har usikker eller dårlig kvalitet.');const values=good.map(x=>x.value),min=Math.min(...values),max=Math.max(...values),sensor=data.sensors.find(s=>s.id===selectedSensor),end=Date.now(),start=end-Number(period)*3600000;const points=good.map(x=>`${40+(Date.parse(x.observed_at)-start)/(end-start)*860},${220-(x.value-min)/(max-min||1)*180}`);return `<div class="chart-meta"><strong>${e(sensor?.name)} <span class="muted">${e(sensor?.unit)}</span></strong><span>Min ${val(min)} · Maks ${val(max)} · ${good.length} gyldige målinger</span></div><svg class="chart" viewBox="0 0 940 270" role="img" aria-label="Måleverdier over tid"><path class="grid" d="M40 40H900 M40 100H900 M40 160H900 M40 220H900"/>${points.map(p=>{const [cx,cy]=p.split(',');return `<circle cx="${cx}" cy="${cy}" r="3"/>`;}).join('')}<text x="40" y="255">${e(time(new Date(start).toISOString()))}</text><text x="780" y="255">${e(time(new Date(end).toISOString()))}</text></svg><p class="chart-note">Punkter viser faktiske målinger. Datagap fylles ikke ut. ${history.length>=10000?'Viser de første 10 000 målingene; velg en kortere periode.':''}</p><details><summary>Vis målinger som tabell</summary>${table(['Tid','Verdi','Kvalitet'],history.slice(-100).reverse().map(r=>`<tr><td>${time(r.observed_at)}</td><td>${val(r.value)} ${e(sensor?.unit)}</td><td>${e(r.quality)}</td></tr>`))}<p class="chart-note">Inntil de siste 100 innlastede målingene.</p></details>`;}
function trends(id){const options=subset('sensors',id);return `<div class="page-heading"><div class="eyebrow">MÅLEDATA</div><h1>Historikk og trender</h1><p>Følg utviklingen i faktiske målinger over tid.</p></div><section class="panel"><div class="filters"><label>Målepunkt<select id="sensor"><option value="">Velg målepunkt</option>${options.map(s=>`<option value="${e(s.id)}" ${selectedSensor===s.id?'selected':''}>${siteName(s.site_id)} · ${e(s.name)} (${e(s.unit)})</option>`).join('')}</select></label><label>Tidsrom<select id="period">${[['1','Siste time'],['24','Siste døgn'],['168','Siste 7 dager'],['720','Siste 30 dager']].map(([v,t])=>`<option value="${v}" ${period===v?'selected':''}>${t}</option>`).join('')}</select></label></div>${chart()}</section><section class="panel"><div class="panel-title"><h2>Hendelseslogg</h2><span class="muted">Siste 50 hendelser</span></div>${eventList(id)}</section>`;}
function reportEnergyBlock(report){
  if(!report?.energy_summary&&!report?.courses?.length)return '';
  const s=report.energy_summary||{};
  const courses=report.courses||[];
  return `<div class="energy-report">
    <div class="energy-summary-grid">
      <article><span>Faktisk varmebruk</span><strong>${val(s.actual_kwh)} kWh</strong><small>Analyseperiode</small></article>
      <article><span>Forventet baseline</span><strong>${val(s.expected_kwh)} kWh</strong><small>Sammenlignbar drift</small></article>
      <article class="${Number(s.deviation_pct)>10?'energy-warn':''}"><span>Avvik</span><strong>${Number(s.deviation_pct)>=0?'+':''}${val(s.deviation_pct)} %</strong><small>${e(s.headline||'')}</small></article>
      <article><span>Analysekonfidens</span><strong>${e(s.confidence||'—')}</strong><small>Avhenger av datagrunnlaget</small></article>
    </div>
    <div class="course-grid">
      ${courses.map(course=>`<article class="course-card ${e(course.status||'unknown')}">
        <div class="course-head"><div><span class="tag">${e(course.device||'ENERGIMÅLER')}</span><h3>${e(course.name)}</h3></div><span class="severity ${course.status==='warning'?'warning':course.status==='normal'?'normal':'unknown'}">${course.status==='warning'?'Bør følges opp':course.status==='normal'?'Normal trend':'Ukjent'}</span></div>
        <div class="course-kpis">
          <div><span>Effekt nå</span><strong>${val(course.power_kw)} kW</strong></div>
          <div><span>Forventet</span><strong>${val(course.expected_power_kw)} kW</strong></div>
          <div><span>Effektavvik</span><strong>${Number(course.power_deviation_pct)>=0?'+':''}${val(course.power_deviation_pct)} %</strong></div>
          <div><span>Flow</span><strong>${val(course.flow_m3h)} m³/h</strong></div>
          <div><span>ΔT nå</span><strong>${val(course.delta_t_k)} K</strong></div>
          <div><span>ΔT start</span><strong>${val(course.delta_t_7d_start)} K</strong></div>
          <div><span>Ventil</span><strong>${val(course.valve_pct)} %</strong></div>
          <div><span>Energi 24 t</span><strong>${val(course.energy_24h_kwh)} kWh</strong></div>
        </div>
        <div class="delta-trend">
          <span>ΔT-trend</span>
          <div class="trend-line"><i style="width:${Math.max(8,Math.min(100,(Number(course.delta_t_k||0)/Math.max(Number(course.delta_t_7d_start||1),1))*100))}%"></i></div>
          <small>${e(course.note||'')}</small>
        </div>
      </article>`).join('')}
    </div>
  </div>`;
}
function reportCard(r){const findings=r.findings||[],attention=findings.filter(f=>f.severity==='warning'||f.severity==='critical').length;return `<article class="report-card"><div class="report-card-head"><span class="tag">${e({draft:'UTKAST',ready:'KLAR',failed:'FEILET'}[r.status]||r.status)}</span><span class="muted">${time(r.period_end)}</span></div><h3>${e(r.title)}</h3><p>${e(r.summary||'Ingen sammendrag tilgjengelig.')}</p><div class="report-card-meta"><span><strong>${attention}</strong> prioriterte funn</span><span><strong>${findings.length}</strong> totale funn</span><span><strong>${e(r.energy_summary?.confidence||'—')}</strong> konfidens</span></div><button class="report-open secondary" data-id="${e(r.id)}">Åpne rapport →</button></article>`;}
function findingsHub(){const findings=allFindings();return findings.length?`<div class="findings-grid">${findings.map(f=>`<article class="finding-hub-card ${e(f.severity||'unknown')}"><div class="finding-hub-top"><span class="severity ${e(f.severity||'unknown')}">${e(findingSeverityLabel(f.severity))}</span><span class="muted">${siteName(f.site_id)}</span></div><h3>${e(f.title)}</h3><p>${e(f.explanation||'')}</p><div class="finding-next"><span>Neste kontroll</span><p>${e(f.check||'Verifiser mot måledata og aktuell driftssituasjon.')}</p></div><button class="text-link report-open" data-id="${e(f.report_id)}">Åpne kilderapport →</button></article>`).join('')}</div>`:blank('✧','Ingen funn å vise','Analysefunn fra rapporter samles her.');}
function reports(){const report=data.reports.find(r=>r.id===selectedReport);const tabs=[['overview','Rapportforslag'],['findings','Alle funn'],['archive','Rapportarkiv'],['method','Analysemetode']];let body='';if(reportTab==='overview')body=data.reports.length?`<div class="report-grid">${data.reports.map(reportCard).join('')}</div>`:blank('▤','Ingen rapporter tilgjengelig','Rapporter vises her når analyser er opprettet.');else if(reportTab==='findings')body=findingsHub();else if(reportTab==='archive')body=data.reports.length?table(['Rapport','Anlegg','Periode','Status',''],data.reports.map(r=>`<tr><td><strong>${e(r.title)}</strong></td><td>${siteName(r.site_id)}</td><td>${time(r.period_start)} – ${time(r.period_end)}</td><td>${e({draft:'Utkast',ready:'Klar',failed:'Feilet'}[r.status])}</td><td><button class="text-link report-open" data-id="${e(r.id)}">Åpne →</button></td></tr>`)):blank('▤','Tomt rapportarkiv','Ingen rapporter er lagret ennå.');else body=`<div class="method-detail-grid"><article><span>01</span><h3>Trendavvik</h3><p>Oppdager gradvise endringer i eksempelvis ΔT, trykk, flow eller energibruk som fortsatt ligger innenfor tradisjonelle alarmgrenser.</p></article><article><span>02</span><h3>Korrelasjonsbrudd</h3><p>Ser på signaler sammen. En verdi kan være normal alene, men kombinasjonen av eksempelvis høy flow og fallende ΔT kan være unormal.</p></article><article><span>03</span><h3>Baseline</h3><p>Sammenligner aktuell drift mot tidligere eller forventet drift under sammenlignbare forhold.</p></article><article><span>04</span><h3>Teknikerbekreftelse</h3><p>Funn presenteres som kontrollforslag. Systemet skal prioritere hvor teknikeren bør se, ikke erstatte faglig verifikasjon.</p></article></div>`;
return `<div class="hero-heading report-hero"><div><div class="eyebrow">ANALYSE · DOKUMENTASJON · OPPFØLGING</div><h1>Analyse & rapporter</h1><p>Gjør rådata om til prioriterte funn, kontrollpunkter og dokumentasjon som kan deles internt eller lagres som PDF.</p></div><div class="report-hero-stat"><strong>${allFindings().length}</strong><span>samlede funn</span></div></div><div class="tabs" role="tablist">${tabs.map(([id,label])=>`<button class="tab-button ${reportTab===id?'active':''}" data-report-tab="${id}">${label}</button>`).join('')}</div><section class="tab-content">${body}</section>
${report?`<section class="panel report-body printable-report"><div class="report-toolbar"><div><span class="eyebrow">DETALJERT ANALYSERAPPORT</span><h2>${e(report.title)}</h2><p>${siteName(report.site_id)} · ${time(report.period_start)} – ${time(report.period_end)}</p></div><div class="report-actions"><button id="print-report" class="secondary">Eksporter / lagre PDF</button><button id="close-report" class="secondary">Lukk</button></div></div><div class="report-executive"><span>Oppsummering</span><p>${e(report.summary)}</p></div>${reportEnergyBlock(report)}${report.findings?.length?`<div class="report-section-heading"><span class="eyebrow">ANALYSEFUNN</span><h3>Hva bør undersøkes?</h3></div>${findingCards(report.findings)}`:''}<div class="report-section-heading"><span class="eyebrow">TEKNISK NOTAT</span><h3>Rapporttekst</h3></div><div class="report-content">${e(report.content||'Rapportinnhold er ikke tilgjengelig ennå.')}</div><div class="pdf-note">PDF: Trykk «Eksporter / lagre PDF» og velg «Lagre som PDF» i utskriftsdialogen.</div></section>`:''}`;}
function integrations(){return `<div class="page-heading"><div class="eyebrow">DATAINNSAMLING</div><h1>Tilkoblinger</h1><p>Datakilder for tekniske anlegg.</p></div><div class="notice">Kun lesing · Plattformen sender ingen kommandoer til ventiler, pumper eller andre komponenter.</div><section class="panel"><div class="panel-title"><h2>Registrerte datakilder</h2></div>${data.integrations.length?table(['Datakilde','Anlegg','Type','Aktivert','Sist sett'],data.integrations.map(i=>`<tr><td>${e(i.name)}</td><td>${siteName(i.site_id)}</td><td>${e(i.kind.toUpperCase())}</td><td>${i.enabled?'Ja':'Nei'}</td><td>${time(i.last_seen_at)}</td></tr>`)):blank('⊞','Ingen datakilder tilkoblet','Datamodellen er klar. Tilkobling til det første anlegget krever oppsett av datainnsamling og mapping av målepunkter.')}</section><div class="integration-cards">${[['MQTT','Meldingsbasert innsamling','Topic og målepunkt-ID kan knyttes til hver sensor.'],['WAGO','Automasjon og gateway','Målepunkter kan kobles til PLS og registeradresser.'],['Belimo','Energi og vannbårne anlegg','Struktur for flow, temperatur, effekt og energi.']].map(([t,s,d])=>`<article class="panel integration"><span class="tag">FORBEREDT · IKKE TILKOBLET</span><h2>${t}</h2><strong>${s}</strong><p>${d}</p></article>`).join('')}</div>`;}
function analysis(){const findings=allFindings(),attention=findings.filter(f=>f.severity==='warning'||f.severity==='critical');return `<div class="hero-heading"><div><div class="eyebrow">SMARTDRIFT ANALYSEMOTOR</div><h1>Fra alarmgrenser til mønstergjenkjenning.</h1><p>Analysehuben viser hva systemet skal lete etter når standard SD-overvåking ikke gir hele bildet.</p></div><div class="hero-chip"><span></span>${isPreview()?'Testdata':'Analysemodell'}</div></div><div class="analysis-stats"><article><span>Prioriterte funn</span><strong>${attention.length}</strong><small>Krever menneskelig verifikasjon</small></article><article><span>Analysekategorier</span><strong>4</strong><small>Trend · korrelasjon · baseline · data</small></article><article><span>Styringsfunksjon</span><strong>0</strong><small>Kun analyse og rådgivning</small></article><article><span>Rapporter</span><strong>${data.reports.length}</strong><small>Dokumentert analysegrunnlag</small></article></div><div class="analysis-engine"><div class="engine-core"><span class="engine-pulse"></span><small>SMARTDRIFT</small><strong>Analyse</strong><p>Tidsserier inn → mønstre ut</p></div><div class="engine-lanes"><article><span>A</span><div><strong>Gradvis avvik</strong><p>Små endringer over timer, dager og uker.</p></div></article><article><span>B</span><div><strong>Signal-sammenheng</strong><p>Kontrollerer om relasjonen mellom målepunkter endres.</p></div></article><article><span>C</span><div><strong>Energi og ytelse</strong><p>Sammenligner effekt, driftstid og baseline.</p></div></article><article><span>D</span><div><strong>Datakvalitet</strong><p>Markerer gap, utdaterte eller usannsynlige målinger.</p></div></article></div></div><section class="panel priority-panel"><div class="panel-title"><div><span class="eyebrow">EKSEMPEL PÅ RESULTAT</span><h2>Prioriterte analysefunn</h2></div>${nav('reports','Alle rapporter →','text-link')}</div>${findingList(attention.length?attention:findings,8)}</section>`;}
function login(){root.innerHTML=`<main class="login-layout"><section class="login-story"><a class="brand logo-brand" href="#${isPreview()?"demo/overview":"overview"}"><img src="/envatec-logo.webp" alt="Envatec" class="brand-logo-image"></a><div><div class="eyebrow">OVERSIKT. INNSIKT. TRYGG DRIFT.</div><h1>Ha kontroll på<br>anleggene dine.</h1><p>Én arbeidsflate for status, målinger og oppfølging av tekniske anlegg.</p><div class="line-art"><span>ANLEGG</span><i></i><span>MÅLINGER</span><i></i><span>INNSIKT</span></div></div><small>VVS &nbsp; / &nbsp; Energi &nbsp; / &nbsp; Teknisk drift</small></section><section class="login-form"><div class="eyebrow">VELKOMMEN TIL ENVATEC SMARTDRIFT</div><h2>Logg inn</h2><p>Bruk kontoen du har fått tilgang med.</p><form id="login-form"><label>E-post<input name="email" type="email" autocomplete="username" placeholder="navn@firma.no" required></label><label>Passord<input name="password" type="password" autocomplete="current-password" required></label><div id="auth-message" role="alert"></div><button type="submit" ${db?'':'disabled'}>Logg inn <span>→</span></button></form>${db?'':'<p class="error">Supabase-tilkoblingen må konfigureres før innlogging.</p>'}<p class="help">Mangler du tilgang? Kontakt den som administrerer anlegget ditt.</p>${nav('demo/overview','Se testanlegg og testrapport →','text-link')}<div class="login-foot">Kun overvåking · Ingen fjernstyring</div></section></main>`;document.querySelector('#login-form').onsubmit=async ev=>{ev.preventDefault();if(!db)return;const button=ev.target.querySelector('button');button.disabled=true;button.textContent='Logger inn …';const form=new FormData(ev.target);try{const {error}=await db.auth.signInWithPassword({email:form.get('email'),password:form.get('password')});if(error)throw error;location.hash='overview';}catch{document.querySelector('#auth-message').textContent='Kunne ikke logge inn. Kontroller e-post og passord, og prøv igjen.';}finally{button.disabled=false;button.textContent='Logg inn →';}};}
function render(){const {page,id}=current();if(activationToken||(passwordSetup&&session)){activation();return;}if(page==='login'&&!session){login();return;}const active=page==='site'?'sites':page==='login'?'overview':page;const content=loading?blank('◷','Henter oversikt …',''):failure?`<div class="error" role="alert"><h2>Kunne ikke hente anleggsdata</h2><p>${e(failure)}</p><button id="retry">Prøv igjen</button></div>`:active==='overview'?overview():active==='sites'&&page!=='site'?`<div class="page-heading"><div class="eyebrow">PORTEFØLJE</div><h1>Anlegg</h1><p>Alle anlegg du har tilgang til.</p></div><section class="panel">${siteList()}</section>`:page==='site'?detail(id):active==='alarms'?`<div class="page-heading"><div class="eyebrow">OPPFØLGING</div><h1>Alarmer</h1><p>Aktive og løste alarmer fra anleggene dine.</p></div><section class="panel">${alarmList()}</section>`:active==='trends'?trends(id):active==='reports'?reports():active==='analysis'?analysis():active==='integrations'?integrations():blank('◫','Siden finnes ikke','',nav('overview','Til oversikten','button'));
root.innerHTML=`<div class="app-layout"><aside class="sidebar"><a class="brand logo-brand" href="#${isPreview()?"demo/overview":"overview"}"><img src="/envatec-logo.webp" alt="Envatec" class="brand-logo-image"></a><div class="workspace"><span class="workspace-icon">${icon("sites")}</span><div>Smartdrift<small>${e(data.organizations[0]?.name||'Anleggsovervåking')}</small></div></div><div class="nav-label">ARBEIDSOMRÅDE</div><nav aria-label="Hovedmeny">${Object.entries(names).map(([k,v])=>nav(k,`<span aria-hidden="true">${icon(k)}</span>${v}${k==='analysis'?'<small>LAB</small>':''}`,active===k?'active':'')).join('')}</nav><div class="sidebar-bottom"><span class="read-only">◉ &nbsp; Kun overvåking</span><p>Lesetilgang til dine anlegg.<br>Ingen fjernstyring.</p><div class="user"><span>${session?'BR':'—'}</span><div>${session?'Innlogget bruker':'Ikke innlogget'}<small>${session?e(session.user.email):(isPreview()?'Testvisning':'Forhåndsvisning uten data')}</small></div></div></div></aside><div class="main-area"><header class="topbar"><div><span class="muted">Arbeidsområde</span><span class="slash">/</span>${e(names[active]||'Anlegg')}</div><div class="top-actions"><span class="connection ${session?'':'offline'}">${session?'Tilkoblet konto':'Ingen konto tilkoblet'}</span>${session?'<button id="logout" class="secondary">Logg ut</button>':nav('login','Logg inn','button small')}</div></header><main class="content">${isPreview()?'<div class="test-notice">TESTVISNING · Anlegg og rapport er illustrasjoner. Ingen liveverdier, faktiske feil eller styring.</div>':!session?'<div class="preview-note">PLATTFORMSTRUKTUR <span>Logg inn for egne data, eller <a href="#demo/overview">åpne testanlegget →</a></span></div>':''}<div class="toolbar"><span>${updated?'Sist hentet '+time(updated):'Ingen driftsdata lastet'}</span><button id="refresh" class="secondary" ${!session||loading?'disabled':''}>${icon("refresh")} Oppdater</button></div>${content}<footer><span>Envatec Smartdrift</span><span>Kun lesing · ${session?'Automatisk oppdatering hvert minutt':'Testinnhold er merket'}</span></footer></main></div></div>`;

 document.querySelector('#refresh')?.addEventListener('click',()=>load());document.querySelector('#retry')?.addEventListener('click',()=>load());document.querySelector('#logout')?.addEventListener('click',async()=>{await db.auth.signOut({scope:'local'});location.hash='login';});
document.querySelector('#sensor')?.addEventListener('change',ev=>{selectedSensor=ev.target.value;loadHistory();});document.querySelector('#period')?.addEventListener('change',ev=>{period=ev.target.value;loadHistory();});document.querySelectorAll('.report-open').forEach(b=>b.onclick=()=>{selectedReport=b.dataset.id;reportTab='overview';if(current().page!=='reports'){location.hash=(isPreview()?'demo/':'')+'reports';}else render();});document.querySelectorAll('[data-report-tab]').forEach(b=>b.onclick=()=>{reportTab=b.dataset.reportTab;selectedReport='';render();});document.querySelector('#close-report')?.addEventListener('click',()=>{selectedReport='';render();});document.querySelector('#print-report')?.addEventListener('click',()=>window.print());}
async function allRows(table){let rows=[];for(let offset=0;;offset+=1000){let q=db.from(table).select('*');if(['events','alarms','reports','analysis_runs'].includes(table)){const col=table==='events'?'occurred_at':table==='alarms'?'occurred_at':'created_at';q=q.order(col,{ascending:false});}else q=q.order(table==='latest_readings'?'sensor_id':'id');const {data:batch,error}=await q.range(offset,offset+999);if(error)throw error;rows.push(...batch);if(batch.length<1000)return rows;if(rows.length>=50000)throw new Error('For mange poster. Kontakt administrator for å avgrense visningen.');}}
async function load(){const token=++generation;if(isPreview()||!session||!db){data=isPreview()?{...emptyData(),...testPreview}:emptyData();loading=false;failure='';render();return;}loading=true;failure='';render();try{const entries=await Promise.all(Object.keys(emptyData()).map(async t=>[t,await allRows(t)]));if(token!==generation)return;data=Object.fromEntries(entries);updated=new Date().toISOString();}catch(err){if(token!==generation)return;data=emptyData();failure='Kontroller nettverk og tilgang til anlegget. Ingen tidligere verdier vises som oppdaterte.';}finally{if(token===generation){loading=false;render();if(current().page==='trends')loadHistory();}}}
async function loadHistory(){const token=++historyGeneration;history=[];historyError='';if(isPreview()||!session||!selectedSensor){historyBusy=false;render();return;}historyBusy=true;render();try{const start=new Date(Date.now()-Number(period)*3600000).toISOString();let rows=[];for(let offset=0;offset<10000;offset+=1000){const {data:batch,error}=await db.from('readings').select('observed_at,value,quality').eq('sensor_id',selectedSensor).gte('observed_at',start).lte('observed_at',new Date().toISOString()).order('observed_at').range(offset,offset+999);if(error)throw error;rows.push(...batch);if(batch.length<1000)break;}if(token===historyGeneration)history=rows;}catch{if(token===historyGeneration)historyError='Kunne ikke hente historikken. Prøv å velge tidsrom på nytt.';}finally{if(token===historyGeneration){historyBusy=false;render();}}}
function activation(){root.innerHTML=`<main class="activation"><div class="login-form"><div class="eyebrow">ENVATEC SMARTDRIFT</div><h2>${passwordSetup?'Velg ditt passord':'Aktiver brukertilgang'}</h2><p>${passwordSetup?'Velg et passord på minst 12 tegn.':'Denne engangslenken aktiverer kontoen din.'}</p><form id="activation-form">${passwordSetup?'<label>Nytt passord<input type="password" name="password" autocomplete="new-password" minlength="12" required></label><label>Gjenta passord<input type="password" name="confirm" autocomplete="new-password" minlength="12" required></label>':''}<div id="activation-message" role="alert"></div><button>${passwordSetup?'Lagre passord':'Aktiver konto'}</button></form></div></main>`;document.querySelector('#activation-form').onsubmit=async ev=>{ev.preventDefault();const button=ev.target.querySelector('button');button.disabled=true;try{if(!db)throw new Error('Tilkoblingen mangler.');if(passwordSetup){const form=new FormData(ev.target);if(form.get('password')!==form.get('confirm'))throw new Error('Passordene er ikke like.');const {error}=await db.auth.updateUser({password:form.get('password')});if(error)throw error;passwordSetup=false;location.hash='overview';load();}else{const token=activationToken;passwordSetup=true;const {error}=await db.auth.verifyOtp({token_hash:token,type:'invite'});if(error){passwordSetup=false;throw new Error('Lenken er utløpt eller allerede brukt. Be administrator om en ny invitasjon.');}activationToken=null;window.history.replaceState(null,'','#set-password');render();}}catch(err){document.querySelector('#activation-message').textContent=err.message;button.disabled=false;}};}
let previousPreview=isPreview();
window.addEventListener('hashchange',()=>{const changed=previousPreview!==isPreview();previousPreview=isPreview();if(location.hash.startsWith('#activate/'))activationToken=location.hash.slice(10);selectedReport='';reportTab='overview';history=[];historyGeneration++;historyBusy=false;selectedSensor='';if(changed){data=emptyData();updated=null;load();}else render();});
if(db){db.auth.onAuthStateChange((event,next)=>{const changed=session?.user.id!==next?.user.id;session=next;if(changed||event==='INITIAL_SESSION'){historyGeneration++;history=[];selectedSensor='';load();}});}else{loading=false;render();}
setInterval(()=>{if(!isPreview()&&session&&!loading&&document.visibilityState==='visible')load();},60000);

import './severity.css';
